const listings = {
        accommodation: [
          {
            title: "Luxury Apartment – Downtown Rajshahi",
            label: "Superb",
            score: "9.2",
            reviews: 87,
            loc: "Rajshahi City Centre",
            dist: "0.8 km from VU",
            type: "2-Bedroom Furnished Flat",
            detail: "2 extra-large rooms, fully furnished",
            price: "৳1,500",
            unit: "/mo",
            tax: "৳200 utilities incl.",
            perks: ["Free maintenance included", "No deposit – pay monthly"],
            emoji: "🏠",
            bg: "bg-accomm",
          },
          {
            title: "Cozy Sublet – University Area",
            label: "Very Good",
            score: "8.6",
            reviews: 42,
            loc: "Near Varendra University",
            dist: "5 min walk to campus",
            type: "Single Room Sublet",
            detail: "1 comfortable room, shared kitchen",
            price: "৳200",
            unit: "/mo",
            tax: "All utilities included",
            perks: ["Free cancellation", "No advance payment needed"],
            emoji: "🛏️",
            bg: "bg-accomm",
          },
          {
            title: "Shared Flat – Campus Road",
            label: "Good",
            score: "7.9",
            reviews: 31,
            loc: "Rajshahi University Road",
            dist: "10 min walk",
            type: "Shared Accommodation",
            detail: "1 bed in 4-person shared flat",
            price: "৳120",
            unit: "/mo",
            tax: "৳30 utilities extra",
            perks: ["Free Wi-Fi", "Weekly cleaning included"],
            emoji: "🏡",
            bg: "bg-accomm",
          },
          {
            title: "Premium Studio – City Hub",
            label: "Exceptional",
            score: "9.5",
            reviews: 112,
            loc: "Central Rajshahi",
            dist: "2 km from VU",
            type: "Private Studio Apartment",
            detail: "Self-contained studio, AC + attached bath",
            price: "৳2,200",
            unit: "/mo",
            tax: "৳350 taxes & charges",
            perks: ["Free cancellation", "Flexible lease terms"],
            emoji: "🏢",
            bg: "bg-accomm",
          },
        ],
        catering: [
          {
            title: "Home Catering – Daily Student Meals",
            label: "Excellent",
            score: "9.0",
            reviews: 68,
            loc: "Near Varendra University",
            dist: "Delivery available on campus",
            type: "Daily Meal Package",
            detail: "Lunch + Dinner, Bangladeshi cuisine",
            price: "৳50",
            unit: "/meal",
            tax: "৳300/week package available",
            perks: ["Free delivery on campus", "Customizable menu"],
            emoji: "🍱",
            bg: "bg-cater",
          },
          {
            title: "Vegan Meal Plan – Weekly Package",
            label: "Very Good",
            score: "8.4",
            reviews: 29,
            loc: "Rajshahi City",
            dist: "Home delivery",
            type: "7-Day Vegan Plan",
            detail: "Breakfast + Lunch, organic ingredients",
            price: "৳35",
            unit: "/meal",
            tax: "৳700/week all-in",
            perks: ["Free cancellation", "Allergen-friendly options"],
            emoji: "🥗",
            bg: "bg-cater",
          },
          {
            title: "Tiffin Service – Home Cooked",
            label: "Superb",
            score: "8.9",
            reviews: 54,
            loc: "Rajshahi West",
            dist: "Tiffin delivery 12–2 PM",
            type: "Lunch Tiffin Only",
            detail: "Single home-cooked meal, 3 items + rice",
            price: "৳30",
            unit: "/meal",
            tax: "Monthly plan ৳750",
            perks: ["Consistent daily timing", "Halal certified"],
            emoji: "🍛",
            bg: "bg-cater",
          },
          {
            title: "Event Catering – Group Bookings",
            label: "Good",
            score: "8.1",
            reviews: 19,
            loc: "Rajshahi City",
            dist: "Venue delivery available",
            type: "Bulk / Event Order",
            detail: "Min 20 persons, set menu options",
            price: "৳45",
            unit: "/person",
            tax: "Includes setup & serving",
            perks: ["Free tasting session", "Flexible menu"],
            emoji: "🎉",
            bg: "bg-cater",
          },
        ],
        tutoring: [
          {
            title: "Math Tutoring – High School & University",
            label: "Exceptional",
            score: "9.4",
            reviews: 93,
            loc: "Online / Rajshahi",
            dist: "Flexible timing",
            type: "Private Math Sessions",
            detail: "Algebra, Calculus, Discrete Math",
            price: "৳45",
            unit: "/hr",
            tax: "৳1,500/month (10 sessions)",
            perks: ["First session free trial", "Study materials provided"],
            emoji: "📐",
            bg: "bg-tutor",
          },
          {
            title: "English Language Tutoring – ESL",
            label: "Very Good",
            score: "8.7",
            reviews: 47,
            loc: "Online",
            dist: "Zoom/Google Meet",
            type: "ESL – All Levels",
            detail: "Speaking, Reading, Writing, Listening",
            price: "৳40",
            unit: "/hr",
            tax: "৳1,200/month (8 sessions)",
            perks: ["Free assessment test", "Certificate of progress"],
            emoji: "📖",
            bg: "bg-tutor",
          },
          {
            title: "Physics & Chemistry – HSC & Uni Level",
            label: "Superb",
            score: "9.1",
            reviews: 61,
            loc: "Rajshahi / Online",
            dist: "Home visits available",
            type: "Science Subjects",
            detail: "HSC, A-Level & BSc Physics/Chemistry",
            price: "৳55",
            unit: "/hr",
            tax: "৳800 for 5 sessions",
            perks: ["Free cancellation", "Past paper practice included"],
            emoji: "⚗️",
            bg: "bg-tutor",
          },
          {
            title: "Programming Tutor – Python, C++, Web",
            label: "Exceptional",
            score: "9.6",
            reviews: 108,
            loc: "Online",
            dist: "Screen-share sessions",
            type: "CS & Programming",
            detail: "Python, C++, JavaScript, Web Dev basics",
            price: "৳60",
            unit: "/hr",
            tax: "৳2,000/month unlimited Q&A",
            perks: ["GitHub project help", "Free code review"],
            emoji: "💻",
            bg: "bg-tutor",
          },
        ],
      };
